[versions]
loom = "1.10.+"
mod-publish = "0.8.4"

minecraft = "1.21.8"
parchment = "2025.07.20"
fabric-loader = "0.16.14"
fabric-api = "0.130.0+1.21.8"

[plugins]
loom = { id = "fabric-loom", version.ref = "loom" }
mod-publish = { id = "me.modmuss50.mod-publish-plugin", version.ref = "mod-publish" }

[libraries]
minecraft = { module = "mojang:minecraft", version.ref = "minecraft" }
parchment = { module = "org.parchmentmc.data:parchment-1.21.8", version.ref = "parchment" }
fabric-loader = { module = "net.fabricmc:fabric-loader", version.ref = "fabric-loader" }
fabric-api = { module = "net.fabricmc.fabric-api:fabric-api", version.ref = "fabric-api" }
